config/routes.rb
Rails.application.routes.draw do
  match "/404", to: "errors#not_found", via: :all, as: "not_found"
  match "/500", to: "errors#internal_server_error", via: :all, as: "internal_server_error"

  root "home#show"
  resources :prompts, only: :show
  get "/feed", to: "home#show", defaults: {format: "rss"}

  post "login", to: "sessions#create"
  delete "logout", to: "sessions#destroy"
  get "login", to: "sessions#new"

  resources :admin, only: :index

  resources :active_sessions, only: [:destroy] do
    collection do
      delete "destroy_all"
    end
  end

  # API routes
  namespace :api, constraints: {format: "json"} do
    namespace :v1 do
      resources :random_prompt, only: :index, path: "prompts/random"
      resources :basecamp_prompt, only: :create, path: "prompts/basecamp"

      # Admin only routes
      namespace :admin do
        resources :prompts, only: %i[show index]
      end
    end
  end
end

app/models/active_session.rb
class ActiveSession < ApplicationRecord
  has_secure_token :remember_token

  belongs_to :account
end

app/controllers/active_sessions_controller.rb
class ActiveSessionsController < ApplicationController
  before_action :authenticate_account!

  def destroy
    @active_session = current_account.active_sessions.find(params[:id])
    @active_session.destroy

    if current_account
      redirect_to account_path, notice: "Session deleted."
    else
      forget_active_session
      reset_session
      redirect_to root_path, notice: "Signed out."
    end
  end

  def destroy_all
    forget_active_session
    current_account.active_sessions.destroy_all
    reset_session

    redirect_to root_path, notice: "Signed out."
  end
end

app/helpers/active_sessions_helper.rb
module ActiveSessionsHelper
end

app/views/active_sessions/_active_session.html.erb
<!-- app/views/active_sessions/_active_session.html.erb -->
<tr>
  <td class="whitespace-nowrap py-2 pl-4 pr-2 text-sm font-medium text-gray-900">
    <%= active_session.user_agent %>
  </td>

  <td class="whitespace-nowrap px-2 py-2 text-sm text-gray-500">
    <%= active_session.ip_address %>
  </td>

  <td class="whitespace-nowrap px-2 py-2 text-sm text-gray-500">
    <%= "#{time_ago_in_words(active_session.created_at)} ago" %>
  </td>

  <td class="relative whitespace-nowrap py-2 pl-2 pr-2 text-right text-xs font-medium">
    <%= button_to "Sign Out", active_session_path(active_session), method: :delete, class: "inline-flex items-center justify-center rounded-md border border-transparent bg-sky-500 px-4 py-2 text-sm font-medium text-white shadow-sm hover:bg-indigo-700 focus:outline-none focus:ring-2 focus:ring-indigo-500 focus:ring-offset-2 sm:w-auto" %>
  </td>
</tr>